---
- name: Ensure specified timezone is available | 1
  stat:
    path: '/usr/share/zoneinfo/{{ timezone }}'
  register: register_timezone_specified

- name: Ensure specified timezone is available | 2
  fail:
  when: not register_timezone_specified.stat.exists

- name: Set /etc/localtime
  copy:
    src: '/usr/share/zoneinfo/{{ timezone }}'
    dest: '/etc/localtime'
    remote_src: True

- name: Set /etc/timezone
  copy:
    dest: /etc/timezone
    content: "{{ timezone }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"
